let shopItemsDataAll = [
  {
    id: "gfdsgdfg_alls",
    name: "โกะโจ อนุวัฒน์",
    subname:"เดะมึงเจอกางอาณาเขต",
    price: 45000000,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/meme/img-1.jpg",
  },
  {
    id: "ioytrhndcv_alls",
    name: "ไอนายชูสองนิ้ว",
    subname:"นายชูสองนิ้วพร้อมจะใส่คุณ",
    price: 100,
    desc: "นายชูสองนิ้วพร้อมจะใส่คุณ",
    img: "images/meme/img-2.jpg",
  },
  {
    id: "wuefbncxbsn_alls",
    name: "ไอป้องนั่งหลับ",
    subname:"อาจจะเห็นว่านั่งหลับ เเต่ที่จริงเข้าห้องฝึกกาลเวลา",
    price: 250000,
    desc: "อาจจะเห็นว่านั่งหลับ เเต่ที่จริงเข้าห้องฝึกกาลเวลา",
    img: "images/meme/img-3.jpg",
  },
  {
    id: "thyfhcbcv_alls",
    name: "ลูซิอ้วน",
    subname:"0ver weight support,but he can heal you so shut.",
    price: 300000000000,
    desc: "0ver weight support,but he can heal you so shut.",
    img: "images/meme/img-4.jpg",
  },
  {
    id: "soda_fruit_alls",
    name: "เกียรติกำธร be like",
    subname:"เกียรติกำธรถูกใจสิ่งนี้",
    price: 45,
    desc: "น้ำผลไม้โซดาสุดสดชื่น ชื่นใจทุกครั้งที่ได้กิน ผลไม้สดแท้แน่นอน!!",
    img: "images/meme/img-5.jpg",
  },
  {
    id: "coffee_espresso_alls",
    name: "Espresso",
    price: 45,
    subname:"เอสเปรสโซ",
    desc: "เอสเปรสโซนั่นมีชื่อเสียงและโด่งดังในโลกของกาแฟ แต่ว่าแม้แต่คอกาแฟตัวยงก็ยังไม่รู้จริงๆ ว่าเอสเปรสโซคืออะไร เอสเปรสโซคือกาแฟเข้มข้ม เหมาะสำหรับคนเข้มๆ กินเลยกาแฟไทย!!",
    img: "images/coffee/img-1.1.png",
  },
  {
    id: "coffee_americano_alls",
    name: "Americano",
    subname:"อเมริกาโน่",
    price: 45,
    desc: "อเมริกาโน่ เมนูที่คุณอาจไม่รู้สึกอะไร คิดว่าเป็นเพียงกาแฟธรรมดา แต่ทว่าการชงกลับกลายเป็นที่ชื่นชอบในหมู่คอกาแฟ โดยไม่ต้องกังวลกับคราบนมอุ่นหรือฟองนม ลองดูสิแล้วคุณจะติดใจ!!",
    img: "images/coffee/img-2.png",
  },
  {
    id: "coffee_latte_alls",
    name: "Latte",
    subname:"ลาเต้",
    price: 45,
    desc: "ลาเต้สัญลักษณ์แห่งกาแฟ ซึ่งเป็นเครื่องดื่มที่ร้านกาแฟทั่วโลกต่างหลงใหล รสชาติของกาแฟที่นุ่มนวลและกลมกล่อมทำให้กาแฟประเภทนี้เป็นที่ชื่นชอบทั่วโลก ดังนั้นไปสั่งซะ!!",
    img: "images/coffee/img-3.2.png",
  },
  {
    id: "coffee_cappuccino_alls",
    name: "Cappuccino",
    subname:"คาปูชิโน",
    price: 45,
    desc: "คาปูชิโนคือที่สุดแห่งความลงตัวของกาแฟ ขึ้นชื่อในเรื่องกาแฟผสมฟองนม เสิร์ฟในแก้วกาแฟใบใหญ่โรยด้วยผงช็อกโกแลต คาปูชิโนคือกาแฟชนิดหนึ่งซึ่งได้รับความนิยมมากที่สุดในจักรวาล อยากรู้ต้องลองแล้วป้ะ!!",
    img: "images/coffee/img-4.1.png",
  },
  {
    id: "coffee_mocha_alls",
    name: "Mocha",
    subname:"มอคค่า",
    price: 45,
    desc: "หวานมันกลมกล่อม กลิ่นหรือรสชาติคล้ายถั่ว และมีรสช็อกโกแลต เครื่องดื่มกาแฟใส่นมนี้คือเครื่องดื่มที่มีเอสเปรสโซเป็นหลัก แต่มักจะทำให้สับสนว่ามอคค่าคืออะไร เราไม่อธิบายว่ามอคค่าคืออะไรหรอกนะ อยากรู้ก็มาสั่งเองสิ!!",
    img: "images/coffee/img-5.2.png",
  },
  {
    id: "tea_bobatea_alls",
    name: "Boba Tea",
    subname:"ชานมไข่มุก",
    price: 45,
    desc: "ชานมไข่มุกสูตรแท้จากไต้หวัน ไข่มุกบุกอย่างดีแั้นเองทุกเม็ด รสชาติหวานชื่นใจ เชิญชวนให้ลิ้มลอง!!",
    img: "images/tea/img-6.2.jpg",
  },
  {
    id: "tea_pinkmilk_alls",
    name: "Iced Pink Milk",
    subname:"นมเย็น",
    price: 45,
    desc: "นมเย็นหวานชื่นใจ รสชาติกลมกล่อม ชงอย่างตั้งใจ ต้องมาลองแล้วป้ะ!!",
    img: "images/tea/img-7.1.png",
  },
  {
    id: "tea_freshmilk_alls",
    name: "Fresh Milk",
    subname:"นมสด",
    price: 45,
    desc: "นมสดแท้นำเข้าจากฟาร์มโดยตรง ปลอดสารอันตราย หอม หวาน มัน ",
    img: "images/tea/img-8.3.png",
  },
  {
    id: "tea_greentea_alls",
    name: "Green Tea",
    subname:"ชาเขียว",
    price: 45,
    desc: "ชาเขียวนำเข้าแสนล้ำค่า ชาเขียวสุดแสนอร่อย กลมกล่อมท้าให้ลิ้มลอง!!",
    img: "images/tea/img-9.1.png",
  },
  {
    id: "soda_fruit_alls",
    name: " Iced Thai Tea",
    subname:"ชาไทย",
    price: 45,
    desc: "ชาไทยรสกลมกล่อม หอมอร่อย ชงโดยผู้เชี่ยวชาญกว่า 10 ปี ห้ามพลาดบอกเลยย!!",
    img: "images/tea/img-9-1.1.jpg",
  },
  {
    id: "soda_fruit_alls",
    name: "Fruitsoda",
    subname:"น้ำผลไม้โซดา",
    price: 45,
    desc: "น้ำผลไม้โซดาสุดสดชื่น ชื่นใจทุกครั้งที่ได้กิน ผลไม้สดแท้แน่นอน!!",
    img: "images/soda/img-10.2.jpg",
  },
    {
    id: "soda_raspberry_alls",
    name: "Raspberry Smoothie",
    subname:"ราสเบอร์รี่ สมูทตี้",
    price: 45,
    desc: "ราสเบอร์รี่ สมูทตี้ จากฝีมือเซฟปั้นปรมาจารย์ด้านการทำสมูทตี้ ราสเบอร์รี่ สมูทตี้ ที่รสชาติสุดอร่อยหวานชื่นใจ กินทีไรเหมือนอยู่บนสรวงสวรรค์ ท้าให้ลอง!!",
    img: "images/soda/img-10-1.1.jpg",
  },
    {
    id: "soda_fruit_alls",
    name: "Mango Smoothie",
    subname:"มะม่วงสมูทตี้",
    price: 45,
    desc: "ตอนนี้เซฟปั้นไปเที่ยวฮาวาย เซฟปั้นอยากกินมะม่วงสมูทตี้ เลยทำมันตรงนั้นเลย รสชาติหวาน เปรี้ยว ชื่นใจ กินทีไรอยากไปฮาวายทุกที!!",
    img: "images/soda/img-10-2.1.jpg",
  },
    {
    id: "soda_fruit_alls",
    name: "Blueberry Yogurt Smoothie",
    subname:"บลูเบอร์รี่โยเกิร์ตสมูทตี้",
    price: 45,
    desc: "ในวันที่อากาศร้อนๆ บลูเบอร์รี่โยเกิร์ตสมูทตี้ จากฝีมือเซฟปั้นจะช่วยให้คุณผ่อนคลาย หายกังวลทุกสิ่งอย่าง กินทีเหมือนไปลาดกระบัง",
    img: "images/soda/img-10-3.1.jpg",
  },
    {
    id: "soda_fruit_alls",
    name: "Kiwi Smoothie",
    subname:"กีวีสมูทตี้",
    price: 45,
    desc: "การที่เซฟปั้นจะไปทำงานที่ลาดกระบัง ต้องเจออากาศร้อน กีวีสมูทตี้ จะช่วยให้เซฟปั้นผ่อนคลายไร้กังวล กินทีถึงลาดกระบัง",
    img: "images/soda/img-10-4.1.jpg",
  },
  {
    id: "appetizer_frenchfries_alls",
    name: "French Fries",
    subname:"เฟรนช์ฟรายส์",
    price: 45,
    desc: "มันฝรั่งแท้อย่างดีเก็บมาสดๆใหม่ๆ ทอดด้วยน้ำมันสดใหม่ อร่อยหอมน่าลิ้มลอง!!",
    img: "images/appetizer/img-11.1.jpg",
  },
  {
    id: "appetizer_tempura_alls",
    name: "Tempura",
    subname:"เทปปุระ",
    price: 45,
    desc: "เทปปุระสุดน่าอร่อย นำเข้าจากแดนอาทิตย์อุทัย ที่อันมาจากแดนไกล พลาดมากถ้าไม่ลอง!!",
    img: "images/appetizer/img-12.1.jpg",
  },
  {
    id: "appetizer_toast_alls",
    name: "Toast",
    subname:"ขนมปังปิ้ง",
    price: 45,
    desc: "ขนมปังแท้ๆ หอมนมจากฮอกไกโด เนื้อสัมผัสกรอบนอกนุ่มใน พร้อมเนยดีๆ คัดสรรจากเบลเยี่ยมม ต้องลอง!!",
    img: "images/appetizer/img-13.1.jpg",
  },
  {
    id: "appetizer_minicocktail_alls",
    name: "Mini Cocktail",
    subname:"มินิคอกเทล",
    price: 45,
    desc: "มินิคอกเทล แสนน่ารับประทาน ไส้กรอกจิ๋วที่น่าลิ้มลอง เมื่อคุณได้กินจะอร่อยเกินต้าน จนหยุดไม่ด้ายยย!!",
    img: "images/appetizer/img-14.1.jpg",
  },
  {
    id: "appetizer_gyoza_alls",
    name: "Gyoza",
    subname:"เกี๊ยวซ่า",
    price: 45,
    desc: "เกี๊ยวซ่า กรอบนอกนุ่มใน เนื้อสัตว์แท้ๆ จากต่างประเทศ รับรองอร่อยแน่นอน กดสั่งเลยยยย!!",
    img: "images/appetizer/img-15.1.jpg",
  },
  {
    id: "maindish_kapow_alls",
    name: "Fried stir basil",
    subname:"กะเพรา",
    price: 45,
    desc: "กะเพราสูตรเด็ดเจ็ดมหาสมุทรจาก เซฟต้อลมาสเตอร์เซฟซีซั่น 38 ที่ท่องไปทั่วไทยเพื่อตามหามา หมู เนื้อ เป็ด ไก่ สั่งมาได้หมด เซฟต้อลจัดให้!",
    img: "images/maindish/img-16.1.jpg",
  },
  {
    id: "maindish_pasta_alls",
    name: "Pasta",
    subname:"พาสต้า",
    price: 45,
    desc: "จากการที่เซฟต้อลได้ไปร่ำเรียนที่อีตาลี 19 ปี เซฟต้อลได้บรรลุถึงการทำพาสต้าอย่างแท้จริง เส้นสดอย่างดีจากมือเซฟต้อล ซอสปรุงสดๆร้อนๆ ที่ทุกคนต้องได้ลิ้มลอง!!",
    img: "images/maindish/img-17.1.jpg",
  },
  {
    id: "maindish_steak_alls",
    name: "Steak",
    subname:"สเต็ก",
    price: 45,
    desc: "ระหว่างที่เซฟต้อลไปท่องแดนอีสานอุทัยอยู่ เซฟต้อลได้พบกับสูตรทำสเต็กสุดแสนมหัศจรรย์ ระดับปรมาจารย์มาสอนด้วยตัวเอง ที่ไม่ว่าใครก็ต้านทานไม่ด้ายยย!!",
    img: "images/maindish/img-18.1.jpg",
  },
  {
    id: "maindish_salad_alls",
    name: "Salad",
    subname:"สลัดผัก",
    price: 45,
    desc: "สลัดเพื่อสุขภาพ สำหรับคนคลีนๆ โดยเซฟต้อลคนเดิม เพิ่มเติมคือปลูกผักเองกับมือ ไม่ต้องกลัวสารพิษอันตราย เซฟต้อลดูแลอย่างดี สั่งเถอะครับ เพื่อนสุขภาพของท่าน!!",
    img: "images/maindish/img-19.1.jpg",
  },
  {
    id: "soda_ramen_alls",
    name: "Ramen",
    subname:"ราเมง",
    price: 45,
    desc: "หลังจากเซฟต้อลได้ศึกษาวิชามามากมาย เซฟต้อลเกิดอยากกินราเมงสูตรต้นตำรับจากประเทศญี่ปุ่น น้ำสุดเข้มข้น พร้อมหมูชาชูเนื้อแน่น ไข่ต้มยางมะตูม  หน่อไม้ดอง ต้นหอม แผ่นสาหร่ายและลูกชิ้นนารูโตะสุดคลาสสิค เซฟต้อลเลยเอามาทำเป็นเมนูขายนะแหละ!!",
    img: "images/maindish/img-19-1.2.jpg",
  },
  {
    id: "dessert_cake_alls",
    name: "Cake",
    subname:"เค้ก",
    price: 45,
    desc: "เค้กคุณภาพดีเลิศนำเข้าจากต่างประเทศ ครีมชั้นดีจากนมฮอกไกโด เนื้อขนมปังชั้นดีจากเวนิส ผสมผสานเพื่อสร้างเป็นเค้กสมบูรณ์แบบ!!",
    img: "images/dessert/img-20.1.jpg",
  },
  {
    id: "dessert_cookie_alls",
    name: "Cookie",
    subname:"คุ้กกี้",
    price: 45,
    desc: "คุ้กกี้โฮมเมคทำเอง ทำใหม่สดๆร้อนๆ พึงออกจากเตาเมื่อกี้เลย ลองซักชิ้นมั้ยยยย!!",
    img: "images/dessert/img-21.1.jpg",
  },
  {
    id: "dessert_icecream_alls",
    name: "Ice cream",
    subname:"ไอศกรีม",
    price: 45,
    desc: "ไอศครีมทำเอง ปั่นเองหลังร้าน นมคัดสรรอย่างดี นมแท้ๆจากฮอกไกโด ถ้าคุณลองกินแล้วจะหยุดไม่ด้ายยย!!",
    img: "images/dessert/img-22.1.jpg",
  },
  {
    id: "dessert_pie_alls",
    name: "Pie",
    subname:"พาย",
    price: 45,
    desc: "พายแท้ๆสูตรจากต่างประเทศ แป้งพาบอย่างดีตั้งใจทำสุดๆทุกกระบวนการ ลองกินเถอะครับ ไม่ลองแล้วคุณจะเสียใจ!!",
    img: "images/dessert/img-23.1.jpg",
  },  
  {
    id: "soda_cheesecake_alls",
    name: "Cheesecake",
    subname:"ชีสเค้ก",
    price: 45,
    desc: "ชีสเค้กอย่างดี ที่ทำจากแป้งที่นวดเองกับมือ ปรุงสดใหม่ทุกชิ้น กลิ่นหอมน่าลิ้มลอง ลองซักชิ้นแล้วจะติดใจ!! ",
    img: "images/dessert/img-23-1.2.jpg",
  }
];


