let shopItemsData_eng = [
  {
    id: "gfdsgdfg_eng",
    name: "โกะโจ อนุวัฒน์",
    subname:"เดะมึงเจอกางอาณาเขต",
    price: 45000000,
    type:["Hot","Cold","Frappe"],
    sweet:["0%(Not Sweet)","50%(Less Sweet)","100%(Normal)","200%(Very Sweet)"],
    topping:["boba", "Brown Sugar", "Honey", "Whipped Cream", "Sprinkles" ,"Caramel"],
    desc: "เดะมึงเจอกางอาณาเขต so fucking savage",
    img: "images/meme/img-1.jpg",
  },
  {
    id: "ioytrhndcv_eng",
    name: "ไอนายชูสองนิ้ว",
    subname:"นายชูสองนิ้วพร้อมจะใส่คุณ",
    price: 100,
    type:["Hot","Cold","Frappe"],
    sweet:["0%(Not Sweet)","50%(Less Sweet)","100%(Normal)","200%(Very Sweet)"],
    topping:["boba", "Brown Sugar", "Honey", "Whipped Cream", "Sprinkles" ,"Caramel"],
    desc: "นายชูสองนิ้วพร้อมจะติ้วคุณ",
    img: "images/meme/img-2.jpg",
  },
  {
    id: "wuefbncxbsn_eng",
    name: "ไอป้องนั่งหลับ",
    subname:"อาจจะเห็นว่านั่งหลับ เเต่ที่จริงเข้าห้องฝึกกาลเวลา",
    price: 250000,
    type:["Hot","Cold","Frappe"],
    sweet:["0%(Not Sweet)","50%(Less Sweet)","100%(Normal)","200%(Very Sweet)"],
    topping:["boba", "Brown Sugar", "Honey", "Whipped Cream", "Sprinkles" ,"Caramel"],
    desc: "อาจจะเห็นว่านั่งหลับ เเต่ที่จริงเข้าห้องฝึกกาลเวลา",
    img: "images/meme/img-3.jpg",
  },
  {
    id: "thyfhcbcv_eng",
    name: "ลูซิอ้วน",
    subname:"0ver weight support,but he can heal you so shut.",
    price: 300000000000,
    type:["Hot","Cold","Frappe"],
    sweet:["0%(Not Sweet)","50%(Less Sweet)","100%(Normal)","200%(Very Sweet)"],
    topping:["boba", "Brown Sugar", "Honey", "Whipped Cream", "Sprinkles" ,"Caramel"],
    desc: "0ver weight support,but he can heal you so shut.",
    img: "images/meme/img-4.jpg",
  },
  {
    id: "soda_fruit_eng",
    name: "เกียรติกำธร be like",
    subname:"เกียรติกำธรถูกใจสิ่งนี้",
    price: 45,
    type:["Hot","Cold","Frappe"],
    sweet:["0%(Not Sweet)","50%(Less Sweet)","100%(Normal)","200%(Very Sweet)"],
    topping:["boba", "Brown Sugar", "Honey", "Whipped Cream", "Sprinkles" ,"Caramel"],
    desc: "น้ำผลไม้โซดาสุดสดชื่น ชื่นใจทุกครั้งที่ได้กิน ผลไม้สดแท้แน่นอน!!",
    img: "images/meme/img-5.jpg",
  },
];

// รายการเมนูต่างๆ

// หมวดกาแฟ

let shopItems_coffee_eng = [
  {
    id: "coffee_espresso_eng",
    name: "Espresso",
    subname:"เอสเปรสโซ",
    price: 45,
    type:["Hot","Cold","Frappe"],
    sweet:["0%(Not Sweet)","50%(Less Sweet)","100%(Normal)","200%(Very Sweet)"],
    topping:["boba", "Brown Sugar", "Honey", "Whipped Cream", "Sprinkles" ,"Caramel"],
    desc: "Espresso is famous and famous in the world of coffee. But even avid coffee lovers don't really know. what is espresso Espresso is a strong, strong coffee. Suitable for dark people Let's eat Thai coffee!!",
    img: "images/coffee/img-1.1.png",
  },
  {
    id: "coffee_americano_eng",
    name: "Americano",
    subname:"อเมริกาโน่",
    price: 45,
    type:["Hot","Cold","Frappe"],
    sweet:["0%(Not Sweet)","50%(Less Sweet)","100%(Normal)","200%(Very Sweet)"],
    topping:["boba", "Brown Sugar", "Honey", "Whipped Cream", "Sprinkles" ,"Caramel"],
    desc: "Americano, a menu that you might not feel at all Think of it as just regular coffee. But the brew turned out to be a favorite among coffee lovers. without worrying about warm milk stains or froth. Try it and you'll be hooked!!",
    img: "images/coffee/img-2.png",
  },
  {
    id: "coffee_latte_eng",
    name: "Latte",
    subname:"ลาเต้",
    price: 45,
    type:["Hot","Cold","Frappe"],
    sweet:["0%(Not Sweet)","50%(Less Sweet)","100%(Normal)","200%(Very Sweet)"],
    topping:["boba", "Brown Sugar", "Honey", "Whipped Cream", "Sprinkles" ,"Caramel"],
    desc: "Latte, the symbol of coffee This is a drink that coffee shops around the world are obsessed with. Its smooth and mellow flavor has made it a favorite around the world. So go order!!",
    img: "images/coffee/img-3.2.png",
  },
  {
    id: "coffee_cappuccino_eng",
    name: "Cappuccino",
    subname:"คาปูชิโน",
    price: 45,
    type:["Hot","Cold","Frappe"],
    sweet:["0%(Not Sweet)","50%(Less Sweet)","100%(Normal)","200%(Very Sweet)"],
    topping:["boba", "Brown Sugar", "Honey", "Whipped Cream", "Sprinkles" ,"Caramel"],
    desc: "Cappuccino is the perfect combination of coffee. Famous for coffee mixed with milk froth. Serve in a large coffee mug sprinkled with chocolate powder. Cappuccino is one of the most popular types of coffee in the universe. If you want to know, you have to try it!!",
    img: "images/coffee/img-4.1.png",
  },
  {
    id: "coffee_mocha",
    name: "Mocha",
    subname:"มอคค่า",
    price: 45,
    type:["Hot","Cold","Frappe"],
    sweet:["0%(Not Sweet)","50%(Less Sweet)","100%(Normal)","200%(Very Sweet)"],
    topping:["boba", "Brown Sugar", "Honey", "Whipped Cream", "Sprinkles" ,"Caramel"],
    desc: "sweet and mellow smell or taste like nuts and has a chocolate flavor This milk coffee drink is espresso-based. But it's often confusing what mocha is. We don't explain what mocha is. If you want to know, come and order by yourself!!",
    img: "images/coffee/img-5.2.png",
  },
];

// หมวดชา

let shopItems_tea_eng = [
  {
    id: "tea_bobatea_eng",
    name: "Boba Tea",
    subname:"ชานมไข่มุก",
    price: 45,
    type:["Hot","Cold","Frappe"],
    sweet:["0%(Not Sweet)","50%(Less Sweet)","100%(Normal)","200%(Very Sweet)"],
    topping:["boba", "Brown Sugar", "Honey", "Whipped Cream", "Sprinkles" ,"Caramel"],
    desc: "Boba Tea, authentic recipe from Taiwan. Pearls are well invaded by themselves. sweet taste I invite you to try it!!",
    img: "images/tea/img-6.2.png",
  },
  {
    id: "tea_pinkmilk_eng",
    name: "Iced Pink Milk",
    subname:"นมเย็น",
    price: 45,
    type:["Hot","Cold","Frappe"],
    sweet:["0%(Not Sweet)","50%(Less Sweet)","100%(Normal)","200%(Very Sweet)"],
    topping:["boba", "Brown Sugar", "Honey", "Whipped Cream", "Sprinkles" ,"Caramel"],
    desc: "Sweet and refreshing milk mellow taste intentionally brew You have to come and try it!!",
    img: "images/tea/img-7.1.png",
  },
  {
    id: "tea_freshmilk_eng",
    name: "Fresh Milk",
    subname:"นมสด",
    price: 45,
    type:["Hot","Cold","Frappe"],
    sweet:["0%(Not Sweet)","50%(Less Sweet)","100%(Normal)","200%(Very Sweet)"],
    topping:["boba", "Brown Sugar", "Honey", "Whipped Cream", "Sprinkles" ,"Caramel"],
    desc: "Real fresh milk imported directly from the farm. Free from harmful substances, fragrant, sweet, oily",
    img: "images/tea/img-8.3.png",
  },
  {
    id: "tea_greentea_eng",
    name: "Green Tea",
    subname:"ชาเขียว",
    price: 45,
    type:["Hot","Cold","Frappe"],
    sweet:["0%(Not Sweet)","50%(Less Sweet)","100%(Normal)","200%(Very Sweet)"],
    topping:["boba", "Brown Sugar", "Honey", "Whipped Cream", "Sprinkles" ,"Caramel"],
    desc: "Precious imported green tea Delicious green tea Mellow, challenge to try!!",
    img: "images/tea/img-9.1.png",
  },
  {
    id: "soda_fruit_eng",
    name: " Iced Thai Tea",
    subname:"ชาไทย",
    price: 45,
    type:["Hot","Cold","Frappe"],
    sweet:["0%(Not Sweet)","50%(Less Sweet)","100%(Normal)","200%(Very Sweet)"],
    topping:["boba", "Brown Sugar", "Honey", "Whipped Cream", "Sprinkles" ,"Caramel"],
    desc: "Real thai tea Brew by Skillful chef. You can't miss it!!!",
    img: "images/tea/img-9-1.1.jpg",
  }
];

// หมวดโซดา

let shopItems_soda_eng = [
  {
    id: "soda_fruit_eng",
    name: "Fruitsoda",
    subname:"น้ำผลไม้โซดา",
    price: 45,
    desc: "The freshest soda juice every time you eat it will definitely be fresh!!",
    img: "images/soda/img-10.2.jpg",
  },
    {
    id: "soda_raspberry_eng",
    name: "Raspberry Smoothie",
    subname:"ราสเบอร์รี่ สมูทตี้",
    price: 45,
    desc: "Raspberry Smoothie by Professional Smoothie Chef, Chef Pun make your delicious Raspberry Smoothie. If you want the haven feel try it!!",
    img: "images/soda/img-10-1.1.jpg",
  },
    {
    id: "soda_mango_eng",
    name: "Mango Smoothie",
    subname:"มะม่วงสมูทตี้",
    price: 45,
    desc: "At that time chef Pun went to Hawaii, he want Mango Smoothie you know what he do, He made made it!! Sweet Sour Fresh You will miss Hawaii.",
    img: "images/soda/img-10-2.1.jpg",
  },
    {
    id: "soda_blueberry_eng",
    name: "Blueberry Yogurt Smoothie",
    subname:"บลูเบอร์รี่โยเกิร์ตสมูทตี้",
    price: 45,
    desc: "The sun is so bright. Blueberry Yogurt Smoothie by Chef Pun will make you relax.",
    img: "images/soda/img-10-3.1.jpg",
  },
    {
    id: "soda_kiwi_eng",
    name: "Kiwi Smoothie",
    subname:"กีวีสมูทตี้",
    price: 45,
    desc: "Hot and Wet that the weather that Chef Pun face it when he work in Lat Krabang. Kiwi Smoothie will surly heal him up.",
    img: "images/soda/img-10-4.1.jpg",
  },
];

// หมวดของว่าง

let shopItems_appetizer_eng = [
  {
    id: "appetizer_frenchfries_eng",
    name: "French Fries",
    subname:"เฟรนช์ฟรายส์",
    price: 45,
    type:[],
    sweet:[],
    topping:[],
    desc: "Each fry is coated in a layer of golden crisp that gives way to a soft, welcoming interior. They hit savory and umami with a hint of sweetness and they taste like potatoes, oil, and just the right amount of salt.",
    img: "images/appetizer/img-11.1.jpg",
  },
  {
    id: "appetizer_tempura_eng",
    name: "Tempura",
    subname:"เทปปุระ",
    price: 45,
    type:[],
    sweet:[],
    topping:[],
    desc: "made out of a variety of julienned vegetables and seafood mixed together in tempura batter and deep fried.",
    img: "images/appetizer/img-12.1.jpg",
  },
  {
    id: "appetizer_toast_eng",
    name: "Toast",
    subname:"ขนมปังปิ้ง",
    price: 45,
    type:[],
    sweet:[],
    topping:[],
    desc: "There’s nothing quite like bread for soaking up the charred, smoky flavor of the grill. This recipe works two different ways: first, you can use it as a base for a summertime bruschetta or fancy toast.",
    img: "images/appetizer/img-13.1.jpg",
  },
  {
    id: "appetizer_minicocktail_eng",
    name: "Mini Cocktail",
    subname:"มินิคอกเทล",
    price: 45,
    type:[],
    sweet:[],
    topping:[],
    desc: "The next time you’re tasked with the duty of bringing an appetizer, do yourself (and everyone around you) a favor and whip up these sausage rolls.",
    img: "images/appetizer/img-14.1.jpg",
  },
  {
    id: "appetizer_gyoza_eng",
    name: "Gyoza",
    subname:"เกี๊ยวซ่า",
    price: 45,
    type:[],
    sweet:[],
    topping:[],
    desc: "Filled with ground meat and vegetables and wrapped in a thin dough. Also known as pot stickers, gyoza originated in China",
    img: "images/appetizer/img-15.1.jpg",
  }
];

// หมวดอาหารจานหลัก

let shopItems_maindish_eng = [
  {
    id: "maindish_kapow_eng",
    name: "Fried stir basil",
    subname:"กะเพรา",
    price: 45,
    type:["Cripy Pork","Pork","Chicken","Bacon","Shrimp","Squid"],
    sweet:["Not Spicy","Mild","Spicy","Hot Spicy","Very Hot Spicy"],
    topping:[],
    desc: "7 Oceans kapow form Ton the legendary chef, who travel around the world to recovery the mystic meal.Order it!! Let him do!!",
    img: "images/maindish/img-16.1.jpg",
  },
  {
    id: "maindish_pasta_eng",
    name: "Pasta",
    subname:"พาสต้า",
    price: 45,
    type:["Cripy Pork","Pork","Chicken","Bacon","Shrimp","Squid"],
    sweet:[],
    topping:["Meat Balls","Tempura","Fried Bacon"],
    desc: "19 Years exprienced of learning cooking skill form italy, Chef Ton have powerful skill to cook immortal pasta, fresh pasta 'n sauce wait for you to taste",
    img: "images/maindish/img-17.1.jpg",
  },
  {
    id: "maindish_steak_eng",
    name: "Steak",
    subname:"สเต็ก",
    price: 45,
    type:["Pork","Chicken","Bacon","Shrimp","Beef", "Mutton"],
    sweet:["Rare","Medium Rare","Medium","Medium Well","Well Done"],
    topping:["Ketchup","Chili Sauce", "Mayonnaise","Black Pepper","Gravy"],
    desc: "When Chef Ton travel in the rising sun he found fantastic steak recipe like god of the sun teach him, nobody can't defend thier sin to taste it!!",
    img: "images/maindish/img-18.1.jpg",
  },
  {
    id: "maindish_salad_eng",
    name: "Salad",
    subname:"สลัดผัก",
    price: 45,
    type:["Salad Dressing","Sesame","Italian","Caesar","Thousand Island","Mayonnaise Wasabi"],
    sweet:[],
    topping:[],
    desc: "Salad for your health, Yes serve by chef Ton again but this dish he plants veg by his holy moly hands.Don't worry about toxic cause Chef Ton take care about it!! Order it!! Now!!",
    img: "images/maindish/img-19.1.jpg",
  },
  {
    id: "maindish_ramen_eng",
    name: "Ramen",
    subname:"ราเมง",
    price: 45,
    type:["Pottage","Tom Yum"],
    sweet:[],
    topping:["Shashu Pork" ,"Medium-boiled egg" ,"Narutomaki"],
    desc: "After he learned form godness of japan food Chef Ton has accidenlly taste the origin ramen form japan with intense soup, shachu pork, soft boiled egg, seaweed and naruto meal ball. So chef Ton mix it well for you!!!",
    img: "images/maindish/img-19-1.2.jpg",
  },
];

// หมวดของหวาน

let shopItems_dessert_eng = [
  {
    id: "dessert_cake_eng",
    name: "Cake",
    subname:"เค้ก",
    price: 45,
    type:[],
    sweet:[],
    topping:[],
    desc: "Excellent quality cakes imported from abroad. The best cream from Hokkaido milk, good bread from Venice mix and match to create the perfect cake!!",
    img: "images/dessert/img-20.1.jpg",
  },
  {
    id: "dessert_cookie_eng",
    name: "Cookie",
    subname:"คุ้กกี้",
    price: 45,
    type:[],
    sweet:[],
    topping:[],
    desc: "Homemade cookies, Made fresh and hot, Get out of the oven just now. Do you want to try washing it!!",
    img: "images/dessert/img-21.1.jpg",
  },
  {
    id: "dessert_icecream_eng",
    name: "Ice cream",
    subname:"ไอศกรีม",
    price: 45,
    type:[],
    sweet:[],
    topping:[],
    desc: "Homemade ice cream with hi grade milk form Hokkaido. GIVE ME ONE MORE!!!",
    img: "images/dessert/img-22.1.jpg",
  },
  {
    id: "dessert_pie_eng",
    name: "Pie",
    subname:"พาย",
    price: 45,
    type:[],
    sweet:[],
    topping:[],
    desc: "Original Pie made by luv try it.",
    img: "images/dessert/img-23.1.jpg",
  },  
  {
    id: "dessert_cheesecake_eng",
    name: "Cheesecake",
    subname:"ชีสเค้ก",
    price: 45,
    type:[],
    sweet:[],
    topping:[],
    desc: "Premium cheese cake mix by hand. Fresh, Good smell. Try it you won't regret!!",
    img: "images/dessert/img-23-1.2.jpg",
  }
];


